server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment
  #数据源
  datasource:
    username: root
    password: a1b2c3
    #windows下的地址和数据库名称
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
#    driver-class-name:

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.it.springcloud.entities    # 所有Entity别名类所在包com.it.springcloud.entities

eureka:
  client:
    #    表示将自己注册进入eureka
    register-with-eureka: true
    #    是否从eureka中抓取已有的注册信息，单节点任意，集群必须为true才可配合ribbon使用负载均衡
    fetch-registry: true
    #    将自己注册到那个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      修改主机名称
  instance:
    instance-id: payment8002
    prefer-ip-address: true