server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    #    表示将自己注册进入eureka
    register-with-eureka: true
    #    是否从eureka中抓取已有的注册信息，单节点任意，集群必须为true才可配合ribbon使用负载均衡
    fetch-registry: true
    #    将自己注册到那个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: oder80
    prefer-ip-address: true